package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

import fr.bicomat.Auth.entities.UserQuestion;

/**
 * CarteBancaire generated by hbm2java
 */
@Entity
@Table(name = "client_idclient")
public class ClientIdclient implements java.io.Serializable {

  /**
   * Identifiant de la table.
   */
  private static final long serialVersionUID = 1L;
  private Integer clientIdclient;
  private Integer idCarte;

  
  public ClientIdclient() {
  }

  public ClientIdclient(Integer idCarte) {
    this.idCarte = idCarte;
  }
  
  @Id
  @GeneratedValue(strategy = IDENTITY)

  @Column(name = "client_idclient", unique = true, nullable = false, length = 11)
  public Integer getClientIdclient() {
    return this.clientIdclient;
  }

  public void setClientIdclient(Integer clientIdclient) {
    this.idCarte = clientIdclient;
  }

  @Column(name = "id_carte", nullable = false, length = 11)
  public Integer getIdCarte() {
    return this.idCarte;
  }

  public void setIdCarte(Integer idCarte) {
    this.idCarte = idCarte;
  }
  

}
