package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompteTiers generated by hbm2java
 */
@Entity
@DiscriminatorValue(value = "TIERS")
public class CompteTiers extends Compte implements java.io.Serializable {

	
	/**
	 * Identifiant de serialisation.
	 */
	private static final long serialVersionUID = 1L;
	private String codeActivation;
	private boolean actif = false;
	private Date dateCreation = new Date();
	

	public CompteTiers() {
	}

	public CompteTiers( boolean actif, Date dateCreation) {
	
		this.actif = actif;
		this.dateCreation = dateCreation;
	
	}

	@Column(name = "code_activation", length = 8)
	public String getCodeActivation() {
		return this.codeActivation;
	}

	public void setCodeActivation(String codeActivation) {
		this.codeActivation = codeActivation;
	}

	@Column(name = "actif", nullable = true)
	public boolean isActif() {
		return this.actif;
	}

	public void setActif(boolean actif) {
		this.actif = actif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_creation", nullable = true, length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}



}
