package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conseiller generated by hbm2java
 */
@Entity
@Table(name = "conseiller")
public class Conseiller implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idconseil;
	private String nomConseil;
	private String prenomConseil;
	private Set<Client> clients = new HashSet<Client>(0);

	public Conseiller() {
	}

	public Conseiller(String nomConseil, String prenomConseil) {
		this.nomConseil = nomConseil;
		this.prenomConseil = prenomConseil;
	}

	public Conseiller(String nomConseil, String prenomConseil, Set<Client> clients) {
		this.nomConseil = nomConseil;
		this.prenomConseil = prenomConseil;
		this.clients = clients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idconseil", unique = true, nullable = false)
	public Integer getIdconseil() {
		return this.idconseil;
	}

	public void setIdconseil(Integer idconseil) {
		this.idconseil = idconseil;
	}

	@Column(name = "nom_conseil", nullable = false, length = 30)
	public String getNomConseil() {
		return this.nomConseil;
	}

	public void setNomConseil(String nomConseil) {
		this.nomConseil = nomConseil;
	}

	@Column(name = "prenom_conseil", nullable = false, length = 30)
	public String getPrenomConseil() {
		return this.prenomConseil;
	}

	public void setPrenomConseil(String prenomConseil) {
		this.prenomConseil = prenomConseil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conseiller")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
