package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document")
public class Document implements java.io.Serializable {

	private Integer iddocument;
	private Client client;
	private String nomDoc;
	private String emplacement;

	public Document() {
	}

	public Document(Client client, String nomDoc, String emplacement) {
		this.client = client;
		this.nomDoc = nomDoc;
		this.emplacement = emplacement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddocument", unique = true, nullable = false)
	public Integer getIddocument() {
		return this.iddocument;
	}

	public void setIddocument(Integer iddocument) {
		this.iddocument = iddocument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_idclient", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "nom_doc", nullable = false, length = 45)
	public String getNomDoc() {
		return this.nomDoc;
	}

	public void setNomDoc(String nomDoc) {
		this.nomDoc = nomDoc;
	}

	@Column(name = "emplacement", nullable = false, length = 100)
	public String getEmplacement() {
		return this.emplacement;
	}

	public void setEmplacement(String emplacement) {
		this.emplacement = emplacement;
	}

}
