package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * InfoCompte generated by hbm2java
 */
@Entity
@Table(name = "infoCompte")
public class InfoCompte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idinfoCompte;
	private String libelle;
	private int montantPlafond;
	private int montantMinimum;
	private long tauxInteret;
	private String codeinfo;
	
	
	
	private Set<Compte> comptes = new HashSet<Compte>(0);

	public InfoCompte() {
	}

	public InfoCompte(String libelle, int montantPlafond, int montantMinimum, long tauxInteret) {
		this.libelle = libelle;
		this.montantPlafond = montantPlafond;
		this.montantMinimum = montantMinimum;
		this.tauxInteret = tauxInteret;
	}

	public InfoCompte(String libelle, int montantPlafond, int montantMinimum, long tauxInteret, Set<Compte> comptes) {
		this.libelle = libelle;
		this.montantPlafond = montantPlafond;
		this.montantMinimum = montantMinimum;
		this.tauxInteret = tauxInteret;
		this.comptes = comptes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idinfoCompte", unique = true, nullable = false)
	public Integer getIdinfoCompte() {
		return this.idinfoCompte;
	}

	public void setIdinfoCompte(Integer idinfoCompte) {
		this.idinfoCompte = idinfoCompte;
	}

	@Column(name = "libelle", nullable = false, length = 45)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "codeInfo", nullable = false, length = 45)
	public String getCodeInfo() {
		return this.codeinfo;
	}

	public void setCodeInfo(String codeinfo) {
		this.codeinfo = codeinfo;
	}
	
	@Column(name = "montantPlafond", nullable = false)
	public int getMontantPlafond() {
		return this.montantPlafond;
	}

	public void setMontantPlafond(int montantPlafond) {
		this.montantPlafond = montantPlafond;
	}

	@Column(name = "montantMinimum", nullable = false)
	public int getMontantMinimum() {
		return this.montantMinimum;
	}

	public void setMontantMinimum(int montantMinimum) {
		this.montantMinimum = montantMinimum;
	}

	@Column(name = "tauxInteret", nullable = false, precision = 10, scale = 0)
	public long getTauxInteret() {
		return this.tauxInteret;
	}

	public void setTauxInteret(long tauxInteret) {
		this.tauxInteret = tauxInteret;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "infoCompte")
	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

}
