package fr.bicomat.entities;
// default package
// Generated 8 déc. 2018 07:10:38 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operation generated by hbm2java
 */
@Entity
@Table(name = "operation")
public class Operation implements java.io.Serializable {

	/**
	 * Identifiant de serialization.
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Compte compte;
	private int numOperation;
	private String libelleOperation;
	private Date dateOperation;
	private double montant;
	private String typeOperation = TypeOperation.CREDIT.getType();
	boolean pointer = false;
	boolean opposition = false;
	
	public Operation() {
	}

	public Operation( Compte compte, int numOperation, Date dateOperation, double montant,
			String typeOperation) {

		this.compte = compte;
		this.numOperation = numOperation;
		this.dateOperation = dateOperation;
		this.montant = montant;
		this.typeOperation = typeOperation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcompte", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "compte_idcompte", nullable = false, insertable = true, updatable = false)
	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	@Column(name = "numOperation", nullable = false)
	public int getNumOperation() {
		return this.numOperation;
	}

	public void setNumOperation(int numOperation) {
		this.numOperation = numOperation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateOperation", nullable = false, length = 19)
	public Date getDateOperation() {
		return this.dateOperation;
	}

	public void setDateOperation(Date dateOperation) {
		this.dateOperation = dateOperation;
	}

	@Column(name = "montant", nullable = false, precision = 22, scale = 0)
	public double getMontant() {
		return this.montant;
	}

	public void setMontant(double montant) {
		this.montant = montant;
	}

	@Column(name = "typeOperation", nullable = false, length = 6)
	public String getTypeOperation() {
		return this.typeOperation;
	}

	public void setTypeOperation(String typeOperation) {
		this.typeOperation = typeOperation;
	}
	
	@Column(name = "libelle", nullable = false, length = 45)
	public String getLibelleOperation() {
		return this.libelleOperation;
	}

	public void setLibelleOperation(String libelleOperation) {
		this.libelleOperation = libelleOperation;
	}
	
	
	@Column(name = "pointer", nullable = false, columnDefinition = "TINYINT", length = 1)
	public boolean getPointer() {
		return this.pointer;
	}

	public void setPointer(boolean pointer) {
		this.pointer = pointer;
	}

	@Column(name = "opposition", nullable = false, columnDefinition = "TINYINT", length = 1)
	public boolean getOpposition() {
		return this.opposition;
	}

	public void setOpposition(boolean opposition) {
		this.opposition = opposition;
	}
}
